spring:
  datasource:
    password: sunnatillo5799
    username: postgres
    url: jdbc:postgresql://localhost:5432/online_store
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size:
        10MB

api:
   info:
       title: CazoStore API
       description: This is the CazoStore API by ST2EMX
       version: 1.0
       terms-of-service: https://unicorn.pdp.uz
       contact-name: pdp.uz
       contact-email: john.lgd65@gmail.com
       contact-url: https://pdp.uz
       license-name: Apache 2.0
       license-url: https://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 8080
    url: boom.uz

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs

